import queue
import uuid
import threading
import logging
from db.database import get_connection # Ensure this import path matches your project

logger = logging.getLogger(__name__)

# --- Queue Management ---
job_queue = queue.Queue()

# --- Shared State (Thread Safe) ---
job_lock = threading.Lock()

# Status: 'pending', 'running', 'completed', 'failed'
job_status = {}

# Results: Final scan target list
job_results = {}

# Progress: Real-time data (current_url, visited_count, targets_so_far)
job_progress = {}

# NEW: Global Map to link UUID -> Integer Database ID
uuid_to_db_id = {}

def add_job(url: str, max_pages: int, cookies=None, user_id: int = None) -> str:
    """
    Adds a job to the queue AND creates a persistent record in the database.
    """
    # 1. Generate UUID for API
    job_uuid = str(uuid.uuid4())

    # 2. Open DB Connection
    conn = get_connection()
    
    try:
        # 3. Insert into Scans table (Persistent)
        c = conn.cursor()
        c.execute(
            "INSERT INTO Scans (user_id, target_url, status, start_time) VALUES (?, ?, 'pending', CURRENT_TIMESTAMP)",
            (user_id, url)
        )
        conn.commit()
        
        # 4. Get the INTEGER scan_id generated by DB
        db_scan_id = c.lastrowid
        logger.info(f"Created DB record for Job {job_uuid} -> scan_id: {db_scan_id}")

        # 5. Store the mapping: UUID -> Integer ID
        with job_lock:
            uuid_to_db_id[job_uuid] = db_scan_id

        # 6. Prepare Job Data for Queue
        job_data = {
            "id": job_uuid,                # UUID for API/Frontend
            "db_scan_id": db_scan_id,        # INTEGER ID for DB/Engine
            "url": url,
            "max_pages": max_pages,
            "cookies": cookies
        }
    
        # 7. Update In-Memory Status (Before queueing)
        with job_lock:
            job_queue.put(job_data)
            job_status[job_uuid] = "pending"
            
            # Initialize progress tracking
            job_progress[job_uuid] = {
                "current_url": "",
                "visited_count": 0,
                "found_count": 0,
                "status": "pending",
                "targets_so_far": [] # List to store live targets
            }
    
    except Exception as e:
        logger.error(f"Failed to insert job into DB: {e}")
        conn.rollback()
        raise
    finally:
        conn.close() # Close connection before putting into queue
    
    return job_uuid

# --- Read/Update Functions ---

def get_job_status(job_uuid: str):
    with job_lock:
        return job_status.get(job_uuid)

def set_job_status(job_uuid: str, status: str):
    """
    Updates both in-memory status and Database status.
    """
    # 1. Retrieve DB ID using Global Map
    db_scan_id = uuid_to_db_id.get(job_uuid)
    
    with job_lock:
        job_status[job_uuid] = status
    
    # 2. Update Database if ID exists
    if db_scan_id:
        conn = get_connection()
        try:
            c = conn.cursor()
            c.execute("UPDATE Scans SET status = ? WHERE scan_id = ?", (status, db_scan_id))
            conn.commit()
            logger.info(f"Updated DB Job {job_uuid} (ID: {db_scan_id}) status to {status}")
        except Exception as e:
            logger.error(f"Failed to update DB status for {job_uuid}: {e}")
            conn.rollback()
        finally:
            conn.close()

def get_job_result(job_uuid: str):
    with job_lock:
        return job_results.get(job_uuid)

def set_job_result(job_uuid: str, result):
    """
    Saves result, updates status, and marks 'end_time' in DB.
    """
    # 1. Retrieve DB ID using Global Map
    db_scan_id = uuid_to_db_id.get(job_uuid)
    
    with job_lock:
        job_results[job_uuid] = result
        job_status[job_uuid] = "completed"
        if job_uuid in job_progress:
            job_progress[job_uuid]["status"] = "completed"
        
        # 2. Update Database (Status + End Time)
        if db_scan_id:
            conn = get_connection()
            try:
                c = conn.cursor()
                c.execute("UPDATE Scans SET status = 'completed', end_time = CURRENT_TIMESTAMP WHERE scan_id = ?", (db_scan_id,))
                conn.commit()
                logger.info(f"Job {job_uuid} marked completed in DB.")
            except Exception as e:
                logger.error(f"Failed to update DB status for {job_uuid}: {e}")
                conn.rollback()
            finally:
                conn.close()

def set_job_progress(job_uuid: str, data: dict):
    """
    Updates progress dictionary.
    Data can be counts OR a new target.
    """
    with job_lock:
        if job_uuid in job_progress:
            # Update existing progress
            job_progress[job_uuid].update(data)
            
            # Special Handling: If we got a new target, append it to list
            if "new_target" in data:
                job_progress[job_uuid]["targets_so_far"].append(data["new_target"])
                # Update found_count based on list length
                job_progress[job_uuid]["found_count"] = len(job_progress[job_uuid]["targets_so_far"])
        else:
            # Initialize if missing
            job_progress[job_uuid] = data

def get_job_progress(job_uuid: str):
    with job_lock:
        return job_progress.get(job_uuid)

# --- Worker Logic ---

def process_jobs():
    """
    Infinite loop that runs in a separate thread.
    Waits for a job, runs it, waits for the next one.
    """
    logger.info("Worker thread started. Waiting for jobs...")
    
    while True:
        # 1. Wait for a job (blocks until one arrives)
        job = job_queue.get()
        job_uuid = job['id']
        db_scan_id = job['db_scan_id'] # Extract DB ID from job data
        
        logger.info(f"Worker picked up job: {job_uuid} (DB ID: {db_scan_id})")
        
        # 2. Mark as "running" (Updates DB via set_job_status)
        set_job_status(job_uuid, "running")
        
        try:
            # Define a callback to update progress
            def update_progress(uuid, data):
                set_job_progress(uuid, data)
            
            # 3. Run Scanner
            # Pass 'db_scan_id' (INT) to engine for logging
            from scanner.engine import WebScanner
            scanner = WebScanner(
                url=job['url'],
                max_pages=job['max_pages'],
                cookies=job['cookies'],
                db_scan_id=db_scan_id,     # Pass INT ID here
                job_id=job_uuid,           # Pass UUID here
                callback=update_progress
            )
            
            # This is the heavy part (Playwright + Network)
            results = scanner.scan()
            
            # 4. Save Result
            set_job_result(job_uuid, results)
            logger.info(f"Job {job_uuid} completed successfully.")
            
        except Exception as e:
            logger.exception(f"Job {job_uuid} failed.")
            # Save error as result so user knows
            set_job_result(job_uuid, {"error": str(e)})
            # Note: set_job_result handles the DB update to 'failed' internally? 
            # Actually, we might want explicit 'failed' status:
            set_job_status(job_uuid, "failed")
        
        # 5. Task done (allows queue.Queue to know we finished)
        job_queue.task_done()

def start_worker():
    """
    Starts the worker loop in a background daemon thread.
    """
    t = threading.Thread(target=process_jobs, daemon=True)
    t.start()