import queue
import uuid
import threading
import logging
import time
from db.database import get_connection  # Route A: run from app/, so short imports

logger = logging.getLogger(__name__)

# --- Queue Management ---
job_queue = queue.Queue()

# --- Shared State (Thread Safe) ---
job_lock = threading.Lock()

# Status: 'pending', 'running', 'completed', 'failed'
job_status = {}

# Results: Final scan target list / error dict
job_results = {}

# Progress: Real-time data (current_url, visited_count, targets_so_far, timing)
job_progress = {}

# Attempts: retry counters per job (Feature 4.4)
job_attempts = {}

# Retry configuration (Feature 4.4)
# MAX_RETRIES = number of *additional* tries after the first attempt.
MAX_RETRIES = 2

# Global Map to link UUID -> Integer Database ID
uuid_to_db_id = {}


def add_job(url: str, max_pages: int, cookies=None, user_id: int = None) -> str:
    """
    Adds a job to the queue AND creates a persistent record in the database.
    Feature 4.5: stores queued_at, and start_time/end_time are tracked properly.
    """
    # 1. Generate UUID for API
    job_uuid = str(uuid.uuid4())

    # 2. Open DB Connection
    conn = get_connection()

    try:
        # 3. Insert into Scans table (Persistent)
        # Feature 4.5: start_time should be NULL until the worker actually starts running.
        c = conn.cursor()
        c.execute(
            "INSERT INTO Scans (user_id, target_url, status, start_time) VALUES (?, ?, 'pending', NULL)",
            (user_id, url)
        )
        conn.commit()

        # 4. Get the INTEGER scan_id generated by DB
        db_scan_id = c.lastrowid
        logger.info(f"Created DB record for Job {job_uuid} -> scan_id: {db_scan_id}")

        # 5. Store the mapping: UUID -> Integer ID
        with job_lock:
            uuid_to_db_id[job_uuid] = db_scan_id

        # 6. Prepare Job Data for Queue
        queued_at = time.time()
        job_data = {
            "id": job_uuid,                 # UUID for API/Frontend
            "db_scan_id": db_scan_id,        # INTEGER ID for DB/Engine
            "url": url,
            "max_pages": max_pages,
            "cookies": cookies,
            # Feature 4.5 timing
            "queued_at": queued_at,
            "start_time": None,
            "end_time": None,
            "duration_seconds": None
        }

        # 7. Update In-Memory Status (Before queueing)
        with job_lock:
            job_queue.put(job_data)
            job_status[job_uuid] = "pending"

            # Initialize retry counters
            job_attempts[job_uuid] = 0

            # Initialize progress tracking
            job_progress[job_uuid] = {
                "current_url": "",
                "visited_count": 0,
                "found_count": 0,
                "status": "pending",
                "attempt": 0,
                "max_retries": MAX_RETRIES,
                "last_error": "",
                "targets_so_far": [],  # live targets

                # Feature 4.5 timing fields (epoch seconds)
                "queued_at": queued_at,
                "start_time": None,
                "end_time": None,
                "duration_seconds": None
            }

    except Exception as e:
        logger.error(f"Failed to insert job into DB: {e}")
        conn.rollback()
        raise
    finally:
        conn.close()

    return job_uuid


# --- Read/Update Functions ---

def get_job_status(job_uuid: str):
    with job_lock:
        return job_status.get(job_uuid)


def set_job_status(job_uuid: str, status: str):
    """
    Updates both in-memory status and Database status.
    Feature 4.5: when status becomes 'running' set start_time in progress + DB.
    """
    db_scan_id = uuid_to_db_id.get(job_uuid)

    with job_lock:
        job_status[job_uuid] = status
        if job_uuid in job_progress:
            job_progress[job_uuid]["status"] = status

            # Feature 4.5: mark start_time exactly when we start running (first time only)
            if status == "running" and job_progress[job_uuid].get("start_time") is None:
                job_progress[job_uuid]["start_time"] = time.time()
                job_progress[job_uuid]["duration_seconds"] = None

    if db_scan_id:
        conn = get_connection()
        try:
            c = conn.cursor()
            if status == "running":
                c.execute(
                    "UPDATE Scans SET status = ?, start_time = CURRENT_TIMESTAMP WHERE scan_id = ?",
                    (status, db_scan_id)
                )
            else:
                c.execute(
                    "UPDATE Scans SET status = ? WHERE scan_id = ?",
                    (status, db_scan_id)
                )
            conn.commit()
            logger.info(f"Updated DB Job {job_uuid} (ID: {db_scan_id}) status to {status}")
        except Exception as e:
            logger.error(f"Failed to update DB status for {job_uuid}: {e}")
            conn.rollback()
        finally:
            conn.close()


def get_job_result(job_uuid: str):
    with job_lock:
        return job_results.get(job_uuid)


def set_job_result(job_uuid: str, result):
    """
    Saves result, updates status, and marks 'end_time' in DB.
    Feature 4.5: compute end_time + duration.
    """
    db_scan_id = uuid_to_db_id.get(job_uuid)

    with job_lock:
        job_results[job_uuid] = result
        job_status[job_uuid] = "completed"
        if job_uuid in job_progress:
            job_progress[job_uuid]["status"] = "completed"

            # Feature 4.5 timing: compute end_time + duration
            now = time.time()
            job_progress[job_uuid]["end_time"] = now
            st = job_progress[job_uuid].get("start_time")
            job_progress[job_uuid]["duration_seconds"] = round(now - st, 2) if st else None

    if db_scan_id:
        conn = get_connection()
        try:
            c = conn.cursor()
            c.execute(
                "UPDATE Scans SET status = 'completed', end_time = CURRENT_TIMESTAMP WHERE scan_id = ?",
                (db_scan_id,)
            )
            conn.commit()
            logger.info(f"Job {job_uuid} marked completed in DB.")
        except Exception as e:
            logger.error(f"Failed to update DB completion for {job_uuid}: {e}")
            conn.rollback()
        finally:
            conn.close()


def set_job_progress(job_uuid: str, data: dict):
    """
    Updates progress dictionary.
    Data can be counts OR a new_target.
    """
    with job_lock:
        if job_uuid in job_progress:
            job_progress[job_uuid].update(data)

            # If we got a new target, append it to list
            if "new_target" in data:
                job_progress[job_uuid]["targets_so_far"].append(data["new_target"])
                job_progress[job_uuid]["found_count"] = len(job_progress[job_uuid]["targets_so_far"])
        else:
            job_progress[job_uuid] = data


def get_job_progress(job_uuid: str):
    with job_lock:
        return job_progress.get(job_uuid)


# --- Retry helpers (Feature 4.4) ---

def increment_attempt(job_uuid: str) -> int:
    """Increment and return the current attempt number (1-based for display)."""
    with job_lock:
        prev = job_attempts.get(job_uuid, 0)
        job_attempts[job_uuid] = prev + 1
        if job_uuid in job_progress:
            job_progress[job_uuid]["attempt"] = job_attempts[job_uuid]
        return job_attempts[job_uuid]


def get_attempt(job_uuid: str) -> int:
    with job_lock:
        return job_attempts.get(job_uuid, 0)


def can_retry(job_uuid: str) -> bool:
    """True if we still have retries left (MAX_RETRIES additional tries)."""
    return get_attempt(job_uuid) < (1 + MAX_RETRIES)


def set_job_failure(job_uuid: str, error_message: str):
    """
    Mark job failed (in-memory + DB) and store error result.
    Feature 4.5: compute end_time + duration for failed jobs too.
    """
    with job_lock:
        job_results[job_uuid] = {"error": error_message}
        job_status[job_uuid] = "failed"
        if job_uuid in job_progress:
            job_progress[job_uuid]["status"] = "failed"
            job_progress[job_uuid]["last_error"] = error_message

            # Feature 4.5 timing
            now = time.time()
            job_progress[job_uuid]["end_time"] = now
            st = job_progress[job_uuid].get("start_time")
            job_progress[job_uuid]["duration_seconds"] = round(now - st, 2) if st else None

    db_scan_id = uuid_to_db_id.get(job_uuid)
    if db_scan_id:
        conn = get_connection()
        try:
            c = conn.cursor()
            c.execute(
                "UPDATE Scans SET status = 'failed', end_time = CURRENT_TIMESTAMP WHERE scan_id = ?",
                (db_scan_id,)
            )
            conn.commit()
        except Exception:
            conn.rollback()
            logger.exception("Failed to mark job failed in DB")
        finally:
            conn.close()


# --- Worker Logic ---

def process_jobs():
    """
    Infinite loop that runs in a separate thread.
    Waits for a job, runs it, waits for the next one.
    """
    logger.info("Worker thread started. Waiting for jobs...")

    while True:
        job = job_queue.get()
        job_uuid = job["id"]
        db_scan_id = job["db_scan_id"]

        logger.info(f"Worker picked up job: {job_uuid} (DB ID: {db_scan_id})")

        # Feature 4.4: count attempt (even if you don't do full re-queue yet)
        increment_attempt(job_uuid)

        # Mark as running (also sets start_time in DB + progress for 4.5)
        set_job_status(job_uuid, "running")

        try:
            def update_progress(uuid_, data):
                set_job_progress(uuid_, data)

            # Run Scanner
            from scanner.engine import WebScanner
            scanner = WebScanner(
                url=job["url"],
                max_pages=job["max_pages"],
                cookies=job["cookies"],
                db_scan_id=db_scan_id,
                job_id=job_uuid,
                callback=update_progress
            )

            results = scanner.scan()

            # Save success result (sets end_time + duration)
            set_job_result(job_uuid, results)
            logger.info(f"Job {job_uuid} completed successfully.")

        except Exception as e:
            logger.exception(f"Job {job_uuid} failed.")
            # IMPORTANT FIX: on failure don't call set_job_result (it would mark completed)
            set_job_failure(job_uuid, str(e))

        job_queue.task_done()


def start_worker():
    """
    Starts the worker loop in a background daemon thread.
    """
    t = threading.Thread(target=process_jobs, daemon=True)
    t.start()
